/**
 * Core domain types, finite state machine definitions, and API contracts
 * for the Gametime Checkout Continuity prototype.
 */

// -----------------------------------------------------------------------------
// 1. Surface Identifiers
// -----------------------------------------------------------------------------

export type CheckoutSurface = "desktop_web" | "mobile_web" | "mobile_app";

// -----------------------------------------------------------------------------
// 2. Finite State Machine (FSM) States & Reasons
// -----------------------------------------------------------------------------

export type CheckoutSessionStatus =
  | "ACTIVE" // Session valid, inventory leased, timer running
  | "PRICE_CHANGED" // Upstream marketplace price shifted; requires explicit fan acceptance
  | "PROCESSING" // Order submission initiated; temporary lock acquired
  | "COMPLETED" // Order successfully fulfilled & ticket issued
  | "EXPIRED" // Inventory lease TTL elapsed; hold released back to marketplace
  | "FAILED"; // Payment / authorization declined; recoverable before TTL expires

export type InventoryStatus = "HELD" | "RELEASED" | "PURCHASED";

export type SessionInvalidReason =
  | "TTL_EXPIRED"
  | "INVENTORY_UNAVAILABLE"
  | "PRICE_DRIFT_UNACCEPTED"
  | "CONCURRENT_PROCESSING_CONFLICT"
  | "ALREADY_COMPLETED";

// -----------------------------------------------------------------------------
// 3. Domain Entities
// -----------------------------------------------------------------------------

export interface EventListing {
  id: string;
  eventName: string;
  venueName: string;
  eventDate: string; // ISO 8601 string
  section: string;
  row: string;
  quantity: number;
  imageUrl?: string;
}

export interface PriceBreakdown {
  basePrice: number; // All-in face price per ticket in cents or dollars (e.g. 120.00)
  serviceFee: number; // Transparent upfront fee
  facilityFee: number;
  total: number;
  currency: "USD" | "CAD";
}

export interface PriceDriftNotice {
  previousTotal: number;
  newTotal: number;
  delta: number;
  reason: "SURGE_DYNAMIC_PRICING" | "ZONE_DEAL_RECALCULATION";
  occurredAt: number; // Unix timestamp (ms)
}

export interface CheckoutSession {
  id: string; // Unique session token (UUID v4)
  listing: EventListing;
  status: CheckoutSessionStatus;
  inventoryStatus: InventoryStatus;
  price: PriceBreakdown;
  priceDrift?: PriceDriftNotice; // Populated only when status === 'PRICE_CHANGED'

  // Time-to-Live & Leasing
  createdAt: number; // Unix timestamp (ms)
  expiresAt: number; // Unix timestamp (ms) - strict source of truth
  ttlRemainingMs?: number; // Computed on response for client convenience

  // Multi-Surface & Concurrency Tracking
  originSurface: CheckoutSurface;
  lastResumedSurface?: CheckoutSurface;
  lastActiveAt: number; // Heartbeat / ping timestamp
  activeLock?: {
    lockedBySurface: CheckoutSurface;
    lockedAt: number;
    lockExpiresAt: number; // 30s processing mutex timeout
  };
  idempotencyKey?: string; // Protects against multi-click or cross-device race conditions
  orderId?: string; // Populated upon transition to 'COMPLETED'
}

// -----------------------------------------------------------------------------
// 4. API Request & Response Contracts
// -----------------------------------------------------------------------------

// POST /api/checkout - Initialize a new checkout session
export interface CreateSessionRequest {
  listingId: string;
  surface: CheckoutSurface;
  quantity?: number;
}

export interface CreateSessionResponse {
  success: boolean;
  session: CheckoutSession;
  deepLink: {
    appSchemeUrl: string; // e.g. "gametime://checkout/{id}"
    webFallbackUrl: string; // e.g. "https://gametime.co/checkout/{id}?surface=mobile_web"
  };
}

// GET /api/checkout/[sessionId] - Resume session across any surface
export interface ResumeSessionResponse {
  session: CheckoutSession;
  isStale: boolean;
  canCheckout: boolean; // True ONLY if status === 'ACTIVE' && Date.now() < expiresAt
  deepLink: {
    appSchemeUrl: string;
    webFallbackUrl: string;
  };
}

// POST /api/checkout/[sessionId]/accept-price - Acknowledge price increase
export interface AcceptPriceChangeRequest {
  surface: CheckoutSurface;
  acceptedTotal: number; // Guard: Client must pass the price they are acknowledging
}

export interface AcceptPriceChangeResponse {
  success: boolean;
  session: CheckoutSession;
}

// POST /api/checkout/[sessionId]/complete - Finalize order (with concurrency check)
export interface CompleteCheckoutRequest {
  surface: CheckoutSurface;
  idempotencyKey: string; // Generated by client to ensure exactly-once execution
  paymentMethodStub: {
    type: "APPLE_PAY" | "GOOGLE_PAY" | "CREDIT_CARD";
    lastFour: string;
  };
}

export interface CompleteCheckoutResponse {
  success: boolean;
  orderId?: string;
  session: CheckoutSession;
  error?: {
    code: SessionInvalidReason;
    message: string;
    conflictingSurface?: CheckoutSurface;
  };
}

// POST /api/checkout/[sessionId]/mock - Reviewer Dev Panel Triggers
export type MockTriggerAction =
  | "TRIGGER_PRICE_CHANGE"
  | "FORCE_EXPIRE"
  | "SIMULATE_CONCURRENT_LOCK"
  | "RESET_SESSION";

export interface MockTriggerRequest {
  action: MockTriggerAction;
  priceDelta?: number; // e.g. +15.00
}

export interface MockTriggerResponse {
  success: boolean;
  actionApplied: MockTriggerAction;
  session: CheckoutSession;
}

// -----------------------------------------------------------------------------
// 5. Client Analytics & Continuity Instrumentation Event Specs
// -----------------------------------------------------------------------------

export type ContinuityTelemetryEvent =
  | {
      event: "checkout_session_created";
      sessionId: string;
      surface: CheckoutSurface;
      listingId: string;
    }
  | {
      event: "checkout_continuity_resumed";
      sessionId: string;
      resumingSurface: CheckoutSurface;
      originSurface: CheckoutSurface;
      elapsedSeconds: number;
    }
  | {
      event: "checkout_price_drift_shown";
      sessionId: string;
      delta: number;
      surface: CheckoutSurface;
    }
  | {
      event: "checkout_price_drift_accepted";
      sessionId: string;
      surface: CheckoutSurface;
    }
  | {
      event: "checkout_concurrency_conflict_blocked";
      sessionId: string;
      blockedSurface: CheckoutSurface;
      activeSurface: CheckoutSurface;
    }
  | {
      event: "checkout_completed";
      sessionId: string;
      surface: CheckoutSurface;
      orderId: string;
      total: number;
    }
  | { event: "checkout_expired"; sessionId: string; surface: CheckoutSurface };
